apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 指定命名空间
namespace: default

# 公共标签，应用于所有资源
commonLabels:
  app: python-demo
  environment: production

# 引用资源文件
resources:
  - deployment.yaml
  - service.yaml
