# 用于阿里云镜像仓库的 Secret
apiVersion: v1
kind: Secret
metadata:
  name: aliyun-registry-secret
  namespace: fleet-local
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config> # 阿里云镜像仓库认证信息

---
# 用于 GitHub 仓库的 Secret
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: fleet-local
type: Opaque
data:
  token: <base64-encoded-github-token> # GitHub 个人访问令牌