apiVersion: v1
kind: Service
metadata:
  name: python-demo
  namespace: default
spec:
  type: NodePort
  selector:
    app: python-demo
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500  # 可自定义端口，也可省略让K8s自动分配