FROM m.daocloud.io/docker.io/python:3.8-slim-buster                

WORKDIR /app

COPY . /app

RUN mkdir -p /root/.pip && echo "[global]\ntrusted-host =  pypi.tuna.tsinghua.edu.cn\nindex-url = https://pypi.tuna.tsinghua.edu.cn/simple" > /root/.pip/pip.conf

RUN pip install flask

EXPOSE 5001

# 设置环境变量，指定 version.txt 路径
ENV VERSION_FILE_PATH=/app/version.txt

CMD ["python", "web_demo.py"]
